<!DOCTYPE Dungeon [

<!ELEMENT dungeon (room+)>
<!ELEMENT room (door+, description)>
<!ELEMENT door EMPTY >
<!ELEMENT description (#PCDATA)>
<!ATTLIST dungeon name CDATA #REQUIRED>
<!ATTLIST room id ID #REQUIRED>
<!ATTLIST door name CDATA #REQUIRED>
<!ATTLIST door dest IDREF #REQUIRED>
]>
<dungeon>
	<room id="R0">
		<door name="Norte" dest="R1"/>
		<door name="Sur" dest="R2"/>
		<description>Inicio</description>
	</room>
	<room id="R1">
		<door name="Sur" dest="R0"/>
		<description>Habitación vacía</description>
	</room>
	<room id="R2">
		<door name="Norte" dest="R0"/>
		<description>Habitación pequeña</description>
	</room>
</dungeon>